
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - "8095:1433"
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost,1433", "-U", "sa", "-P", "Password123!", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks: 
      - app-network
  backend:
    build:
      context: ../
      dockerfile: HobbyMatchAPI/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=HobbyDB;User=sa;Password=Password123!;TrustServerCertificate=True;
      - JwtOptions__Secret=dd1c71000392f2c295462b528863520aa8f486df2ac726c1f40ac25f43b9673910affe99f207c57e08cdb9f0c30c106f3899d4470b623643910a6244f32809a83e86bd103802ad7c3380a816ebc77a0c0b174204ccb1af7367de1db8d2f9b0893ac7f27704bc5a4f92e1aa07dcbfe63ac93a05b50a57bbf82c55f91a753dc58dcfdeb80b4dd2e27c2e013fe1fbe2c4cb52f2c2ad0d30f2252be32e3689542ea622a5068babbd45bd2d2c0eb7abad79bc2baabe499d7ec0f0e2bd53ddf50a984ab08a6bec8fbeabf9a30d84369bda625667ae4606f793fdc813369b455f167504a0d746ba0702b6e65dcdedaa8b4838b742fd286695a14f34a06ce37c6044c8c4
      - JwtOptions__ExpirationTime=15
      - JwtOptions__Issuer=http://backend:8080
      - JwtOptions__Audience=http://frontend:8080
    networks:
      - app-network
  frontend:
    build: 
      context: ../
      dockerfile: HobbyMatchApp/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - backend
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings__BaseUrl=http://backend:8080/api/
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
    
volumes:
  sqlserver_data: